### ISSUE TITLE
Requires a node version greater than v0.0.25

### ISSUE THREAD

**Issue by mathwhiz1212** [Daplie/daplie-tools#1]
uname -a
Linux livetolearntech 3.2.34-30 #17 SMP Mon Apr 13 15:53:45 UTC 2015 armv7l armv7l armv7l GNU/Linux

Solution: My server host is using servers with an obscure ARMv7 based architecture and is slow to compile new versions of software sometimes. I was told to make sure my node version was 4.x or greater.
I ran: node --version and I laughed, output: v0.10.25

Error Message:

Enter your Passphrase (↑ to show): [oauth3-cli] Error createCredential
Error: No callback provided to pbkdf2
    at Object.exports.pbkdf2 (crypto.js:554:11)
    at /usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/pbkdf2-utils.js:33:12
    at Promise._execute (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:77:14)
    at getProofOfSecret (/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/pbkdf2-utils.js:32:10)
    at Object.A3.createCredential (/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/utils.js:614:10)
    at Object.CLI.createCredential (/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:1168:6)
    at loginHelper (/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:1990:11)
    at loopit (/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:1957:5)
    at /usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:847:5
    at /usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:628:5
    at callback (/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:654:5)
    at ReadStream.onData (/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:673:9)
    at ReadStream.EventEmitter.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:746:14)
    at ReadStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at ReadStream.Readable.push (_stream_readable.js:127:10)
    at TTY.onread (net.js:526:21)
undefined

**Comment by mathwhiz1212** [comment]
Apparently  v0.10.25 is the default for Ubuntu 14.04 LTS and derivatives.
