### ISSUE TITLE
Needs bettor error message for missing tld

### ISSUE THREAD

**Issue by coolaj86** [Daplie/daplie-tools#10]
Try this, for example:

`daplie devices:detach -d test-all-the-things -n anonymous`

**Comment by mathwhiz1212** [comment]
Installed earlier today and this error is what I get when I run above command:

Possibly Unhandled Rejection at:
Error: tld '' does not match known tld list
    at /usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:2502:30
    at tryCatcher (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by coolaj86** [comment]
Note: wrap code blocks in triple backticks:

    ```

Also, yes, you are correct. This is why it needs a better error message. :-)

**Comment by mathwhiz1212** [comment]
Will do. I'm thinking for no TLD tell them something along the lines of: "Please add a TLD to the domain name. e.g .com, .net, .cloud etc." and for a TLD that isn't on the list we could say something like: "Sorry, We don't have the TLD you entered."

**Comment by coolaj86** [comment]
Implement it and pull request. :)

I'm good with that working for now, we can tweak it later if needed.

**Comment by mathwhiz1212** [comment]
What do you think of  "Sorry, We don't have the TLD you entered. Please try another one or request one at aj@daplie.com"

**Comment by mathwhiz1212** [comment]
Done: https://github.com/OAuth3/oauth3-cli/pull/10

**Comment by brysonchill** [comment]
Should be support@daplie.com (or something like that - AJ to advise) - don't want too many emails going directly to AJ's email.

**Comment by coolaj86** [comment]
I definitely do want it going directly to my email - it's no good going to yours, but yes domains@daplie.com or support@daplie.com would be best - both of which already go directly to my email.

**Comment by brysonchill** [comment]
Make the change to domains@daplie.com

**Comment by mathwhiz1212** [comment]
Apparently I don't know what I was supposed to be doing as shown here: https://github.com/OAuth3/oauth3-cli/pull/10 New error message: Sorry, We don't have the TLD you entered. Please try another one or email domains@daplie.com and request one.

**Comment by brysonchill** [comment]
Looks good! Thanks!
