### ISSUE TITLE
Incorrect password will crash the program.

### ISSUE THREAD

**Issue by mathwhiz1212** [Daplie/daplie-tools#4]
Incorrect password will crash the program giving this error:

 [oauth3-cli] login Error:
Error: The passphrase you provided is incorrect.
    at /usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:1416:15
    at tryCatcher (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:629:18)
    at Request._callback (/usr/local/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/nodeback.js:42:21)
    at Request.self.callback (/usr/local/lib/node_modules/daplie-tools/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
{ error: 'E_INVALID_SECRET',
  error_description: 'The passphrase you provided is incorrect.',
  error_uri: 'https://oauth3.org/docs/errors/#E_INVALID_SECRET',
  accessToken: undefined,
  refreshToken: undefined,
  expiresIn: undefined,
  expiresAt: undefined }

**Comment by coolaj86** [comment]
Yeah... none of the error cases are handled very gracefully yet.
